'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace PlaylistService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="PlaylistService.ServiceSoap")>  _
    Public Interface ServiceSoap
        
        'CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/login", ReplyAction:="*")>  _
        Function login(ByVal request As PlaylistService.loginRequest) As PlaylistService.loginResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/logout", ReplyAction:="*")>  _
        Sub logout()
        
        'CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getClientPlaylistCollection", ReplyAction:="*")>  _
        Function getClientPlaylistCollection(ByVal request As PlaylistService.getClientPlaylistCollectionRequest) As PlaylistService.getClientPlaylistCollectionResponse
        
        'CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getPlaylist", ReplyAction:="*")>  _
        Function getPlaylist(ByVal request As PlaylistService.getPlaylistRequest) As PlaylistService.getPlaylistResponse
        
        'CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/createNewClient", ReplyAction:="*")>  _
        Function createNewClient(ByVal request As PlaylistService.createNewClientRequest) As PlaylistService.createNewClientResponse
        
        'CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/createNewPlayList", ReplyAction:="*")>  _
        Function createNewPlayList(ByVal request As PlaylistService.createNewPlayListRequest) As PlaylistService.createNewPlayListResponse
        
        'CODEGEN: Generating message contract since element name playname from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/createNewTrack", ReplyAction:="*")>  _
        Function createNewTrack(ByVal request As PlaylistService.createNewTrackRequest) As PlaylistService.createNewTrackResponse
        
        'CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/updateClientName", ReplyAction:="*")>  _
        Function updateClientName(ByVal request As PlaylistService.updateClientNameRequest) As PlaylistService.updateClientNameResponse
        
        'CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/updatePlaylistName", ReplyAction:="*")>  _
        Function updatePlaylistName(ByVal request As PlaylistService.updatePlaylistNameRequest) As PlaylistService.updatePlaylistNameResponse
        
        'CODEGEN: Generating message contract since element name playname from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getTrackInfo", ReplyAction:="*")>  _
        Function getTrackInfo(ByVal request As PlaylistService.getTrackInfoRequest) As PlaylistService.getTrackInfoResponse
        
        'CODEGEN: Generating message contract since element name playname from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/updateTrack", ReplyAction:="*")>  _
        Function updateTrack(ByVal request As PlaylistService.updateTrackRequest) As PlaylistService.updateTrackResponse
        
        'CODEGEN: Generating message contract since element name playname from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/removeTrack", ReplyAction:="*")>  _
        Function removeTrack(ByVal request As PlaylistService.removeTrackRequest) As PlaylistService.removeTrackResponse
        
        'CODEGEN: Generating message contract since element name playname from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/removePlaylist", ReplyAction:="*")>  _
        Function removePlaylist(ByVal request As PlaylistService.removePlaylistRequest) As PlaylistService.removePlaylistResponse
        
        'CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/removeClient", ReplyAction:="*")>  _
        Function removeClient(ByVal request As PlaylistService.removeClientRequest) As PlaylistService.removeClientResponse
        
        'CODEGEN: Generating message contract since element name playname from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/voteOnPlaylist", ReplyAction:="*")>  _
        Function voteOnPlaylist(ByVal request As PlaylistService.voteOnPlaylistRequest) As PlaylistService.voteOnPlaylistResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class loginRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="login", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PlaylistService.loginRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PlaylistService.loginRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class loginRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public username As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal username As String, ByVal password As String)
            MyBase.New
            Me.username = username
            Me.password = password
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class loginResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="loginResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PlaylistService.loginResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PlaylistService.loginResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class loginResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public loginResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal loginResult As Boolean)
            MyBase.New
            Me.loginResult = loginResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getClientPlaylistCollectionRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getClientPlaylistCollection", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PlaylistService.getClientPlaylistCollectionRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PlaylistService.getClientPlaylistCollectionRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getClientPlaylistCollectionRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public nickname As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nickname As String)
            MyBase.New
            Me.nickname = nickname
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getClientPlaylistCollectionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getClientPlaylistCollectionResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PlaylistService.getClientPlaylistCollectionResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PlaylistService.getClientPlaylistCollectionResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getClientPlaylistCollectionResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public getClientPlaylistCollectionResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getClientPlaylistCollectionResult As String)
            MyBase.New
            Me.getClientPlaylistCollectionResult = getClientPlaylistCollectionResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getPlaylistRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getPlaylist", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PlaylistService.getPlaylistRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PlaylistService.getPlaylistRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getPlaylistRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public nickname As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public playname As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nickname As String, ByVal playname As String)
            MyBase.New
            Me.nickname = nickname
            Me.playname = playname
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getPlaylistResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getPlaylistResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PlaylistService.getPlaylistResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PlaylistService.getPlaylistResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getPlaylistResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public getPlaylistResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getPlaylistResult As String)
            MyBase.New
            Me.getPlaylistResult = getPlaylistResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class createNewClientRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="createNewClient", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PlaylistService.createNewClientRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PlaylistService.createNewClientRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class createNewClientRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public nickname As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nickname As String)
            MyBase.New
            Me.nickname = nickname
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class createNewClientResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="createNewClientResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PlaylistService.createNewClientResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PlaylistService.createNewClientResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class createNewClientResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public createNewClientResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal createNewClientResult As Boolean)
            MyBase.New
            Me.createNewClientResult = createNewClientResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class createNewPlayListRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="createNewPlayList", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PlaylistService.createNewPlayListRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PlaylistService.createNewPlayListRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class createNewPlayListRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public nickname As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public playlistname As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nickname As String, ByVal playlistname As String)
            MyBase.New
            Me.nickname = nickname
            Me.playlistname = playlistname
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class createNewPlayListResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="createNewPlayListResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PlaylistService.createNewPlayListResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PlaylistService.createNewPlayListResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class createNewPlayListResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public createNewPlayListResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal createNewPlayListResult As Boolean)
            MyBase.New
            Me.createNewPlayListResult = createNewPlayListResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class createNewTrackRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="createNewTrack", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PlaylistService.createNewTrackRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PlaylistService.createNewTrackRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class createNewTrackRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public playname As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public trackTitle As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public urlLocation As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public duration As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal playname As String, ByVal trackTitle As String, ByVal urlLocation As String, ByVal duration As String)
            MyBase.New
            Me.playname = playname
            Me.trackTitle = trackTitle
            Me.urlLocation = urlLocation
            Me.duration = duration
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class createNewTrackResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="createNewTrackResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PlaylistService.createNewTrackResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PlaylistService.createNewTrackResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class createNewTrackResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public createNewTrackResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal createNewTrackResult As Boolean)
            MyBase.New
            Me.createNewTrackResult = createNewTrackResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class updateClientNameRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="updateClientName", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PlaylistService.updateClientNameRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PlaylistService.updateClientNameRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class updateClientNameRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public nickname As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public newClientNickName As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nickname As String, ByVal newClientNickName As String)
            MyBase.New
            Me.nickname = nickname
            Me.newClientNickName = newClientNickName
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class updateClientNameResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="updateClientNameResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PlaylistService.updateClientNameResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PlaylistService.updateClientNameResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class updateClientNameResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public updateClientNameResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal updateClientNameResult As Boolean)
            MyBase.New
            Me.updateClientNameResult = updateClientNameResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class updatePlaylistNameRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="updatePlaylistName", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PlaylistService.updatePlaylistNameRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PlaylistService.updatePlaylistNameRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class updatePlaylistNameRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public nickname As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public playname As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public newPlayname As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nickname As String, ByVal playname As String, ByVal newPlayname As String)
            MyBase.New
            Me.nickname = nickname
            Me.playname = playname
            Me.newPlayname = newPlayname
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class updatePlaylistNameResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="updatePlaylistNameResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PlaylistService.updatePlaylistNameResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PlaylistService.updatePlaylistNameResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class updatePlaylistNameResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public updatePlaylistNameResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal updatePlaylistNameResult As Boolean)
            MyBase.New
            Me.updatePlaylistNameResult = updatePlaylistNameResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getTrackInfoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getTrackInfo", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PlaylistService.getTrackInfoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PlaylistService.getTrackInfoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getTrackInfoRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public playname As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public trackID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal playname As String, ByVal trackID As String)
            MyBase.New
            Me.playname = playname
            Me.trackID = trackID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getTrackInfoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getTrackInfoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PlaylistService.getTrackInfoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PlaylistService.getTrackInfoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getTrackInfoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public getTrackInfoResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getTrackInfoResult As String)
            MyBase.New
            Me.getTrackInfoResult = getTrackInfoResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class updateTrackRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="updateTrack", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PlaylistService.updateTrackRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PlaylistService.updateTrackRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class updateTrackRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public playname As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public trackID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public title As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public location As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public duration As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal playname As String, ByVal trackID As String, ByVal title As String, ByVal location As String, ByVal duration As String)
            MyBase.New
            Me.playname = playname
            Me.trackID = trackID
            Me.title = title
            Me.location = location
            Me.duration = duration
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class updateTrackResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="updateTrackResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PlaylistService.updateTrackResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PlaylistService.updateTrackResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class updateTrackResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public updateTrackResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal updateTrackResult As Boolean)
            MyBase.New
            Me.updateTrackResult = updateTrackResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class removeTrackRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="removeTrack", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PlaylistService.removeTrackRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PlaylistService.removeTrackRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class removeTrackRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public playname As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public trackID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal playname As String, ByVal trackID As String)
            MyBase.New
            Me.playname = playname
            Me.trackID = trackID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class removeTrackResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="removeTrackResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PlaylistService.removeTrackResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PlaylistService.removeTrackResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class removeTrackResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public removeTrackResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal removeTrackResult As Boolean)
            MyBase.New
            Me.removeTrackResult = removeTrackResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class removePlaylistRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="removePlaylist", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PlaylistService.removePlaylistRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PlaylistService.removePlaylistRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class removePlaylistRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public playname As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal playname As String)
            MyBase.New
            Me.playname = playname
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class removePlaylistResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="removePlaylistResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PlaylistService.removePlaylistResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PlaylistService.removePlaylistResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class removePlaylistResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public removePlaylistResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal removePlaylistResult As Boolean)
            MyBase.New
            Me.removePlaylistResult = removePlaylistResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class removeClientRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="removeClient", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PlaylistService.removeClientRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PlaylistService.removeClientRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class removeClientRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public nickname As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nickname As String)
            MyBase.New
            Me.nickname = nickname
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class removeClientResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="removeClientResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PlaylistService.removeClientResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PlaylistService.removeClientResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class removeClientResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public removeClientResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal removeClientResult As Boolean)
            MyBase.New
            Me.removeClientResult = removeClientResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class voteOnPlaylistRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="voteOnPlaylist", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PlaylistService.voteOnPlaylistRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PlaylistService.voteOnPlaylistRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class voteOnPlaylistRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public playname As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public score As Double
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal playname As String, ByVal score As Double)
            MyBase.New
            Me.playname = playname
            Me.score = score
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class voteOnPlaylistResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="voteOnPlaylistResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PlaylistService.voteOnPlaylistResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PlaylistService.voteOnPlaylistResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class voteOnPlaylistResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public voteOnPlaylistResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal voteOnPlaylistResult As Boolean)
            MyBase.New
            Me.voteOnPlaylistResult = voteOnPlaylistResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ServiceSoapChannel
        Inherits PlaylistService.ServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of PlaylistService.ServiceSoap)
        Implements PlaylistService.ServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PlaylistService_ServiceSoap_login(ByVal request As PlaylistService.loginRequest) As PlaylistService.loginResponse Implements PlaylistService.ServiceSoap.login
            Return MyBase.Channel.login(request)
        End Function
        
        Public Function login(ByVal username As String, ByVal password As String) As Boolean
            Dim inValue As PlaylistService.loginRequest = New PlaylistService.loginRequest()
            inValue.Body = New PlaylistService.loginRequestBody()
            inValue.Body.username = username
            inValue.Body.password = password
            Dim retVal As PlaylistService.loginResponse = CType(Me,PlaylistService.ServiceSoap).login(inValue)
            Return retVal.Body.loginResult
        End Function
        
        Public Sub logout() Implements PlaylistService.ServiceSoap.logout
            MyBase.Channel.logout
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PlaylistService_ServiceSoap_getClientPlaylistCollection(ByVal request As PlaylistService.getClientPlaylistCollectionRequest) As PlaylistService.getClientPlaylistCollectionResponse Implements PlaylistService.ServiceSoap.getClientPlaylistCollection
            Return MyBase.Channel.getClientPlaylistCollection(request)
        End Function
        
        Public Function getClientPlaylistCollection(ByVal nickname As String) As String
            Dim inValue As PlaylistService.getClientPlaylistCollectionRequest = New PlaylistService.getClientPlaylistCollectionRequest()
            inValue.Body = New PlaylistService.getClientPlaylistCollectionRequestBody()
            inValue.Body.nickname = nickname
            Dim retVal As PlaylistService.getClientPlaylistCollectionResponse = CType(Me,PlaylistService.ServiceSoap).getClientPlaylistCollection(inValue)
            Return retVal.Body.getClientPlaylistCollectionResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PlaylistService_ServiceSoap_getPlaylist(ByVal request As PlaylistService.getPlaylistRequest) As PlaylistService.getPlaylistResponse Implements PlaylistService.ServiceSoap.getPlaylist
            Return MyBase.Channel.getPlaylist(request)
        End Function
        
        Public Function getPlaylist(ByVal nickname As String, ByVal playname As String) As String
            Dim inValue As PlaylistService.getPlaylistRequest = New PlaylistService.getPlaylistRequest()
            inValue.Body = New PlaylistService.getPlaylistRequestBody()
            inValue.Body.nickname = nickname
            inValue.Body.playname = playname
            Dim retVal As PlaylistService.getPlaylistResponse = CType(Me,PlaylistService.ServiceSoap).getPlaylist(inValue)
            Return retVal.Body.getPlaylistResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PlaylistService_ServiceSoap_createNewClient(ByVal request As PlaylistService.createNewClientRequest) As PlaylistService.createNewClientResponse Implements PlaylistService.ServiceSoap.createNewClient
            Return MyBase.Channel.createNewClient(request)
        End Function
        
        Public Function createNewClient(ByVal nickname As String) As Boolean
            Dim inValue As PlaylistService.createNewClientRequest = New PlaylistService.createNewClientRequest()
            inValue.Body = New PlaylistService.createNewClientRequestBody()
            inValue.Body.nickname = nickname
            Dim retVal As PlaylistService.createNewClientResponse = CType(Me,PlaylistService.ServiceSoap).createNewClient(inValue)
            Return retVal.Body.createNewClientResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PlaylistService_ServiceSoap_createNewPlayList(ByVal request As PlaylistService.createNewPlayListRequest) As PlaylistService.createNewPlayListResponse Implements PlaylistService.ServiceSoap.createNewPlayList
            Return MyBase.Channel.createNewPlayList(request)
        End Function
        
        Public Function createNewPlayList(ByVal nickname As String, ByVal playlistname As String) As Boolean
            Dim inValue As PlaylistService.createNewPlayListRequest = New PlaylistService.createNewPlayListRequest()
            inValue.Body = New PlaylistService.createNewPlayListRequestBody()
            inValue.Body.nickname = nickname
            inValue.Body.playlistname = playlistname
            Dim retVal As PlaylistService.createNewPlayListResponse = CType(Me,PlaylistService.ServiceSoap).createNewPlayList(inValue)
            Return retVal.Body.createNewPlayListResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PlaylistService_ServiceSoap_createNewTrack(ByVal request As PlaylistService.createNewTrackRequest) As PlaylistService.createNewTrackResponse Implements PlaylistService.ServiceSoap.createNewTrack
            Return MyBase.Channel.createNewTrack(request)
        End Function
        
        Public Function createNewTrack(ByVal playname As String, ByVal trackTitle As String, ByVal urlLocation As String, ByVal duration As String) As Boolean
            Dim inValue As PlaylistService.createNewTrackRequest = New PlaylistService.createNewTrackRequest()
            inValue.Body = New PlaylistService.createNewTrackRequestBody()
            inValue.Body.playname = playname
            inValue.Body.trackTitle = trackTitle
            inValue.Body.urlLocation = urlLocation
            inValue.Body.duration = duration
            Dim retVal As PlaylistService.createNewTrackResponse = CType(Me,PlaylistService.ServiceSoap).createNewTrack(inValue)
            Return retVal.Body.createNewTrackResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PlaylistService_ServiceSoap_updateClientName(ByVal request As PlaylistService.updateClientNameRequest) As PlaylistService.updateClientNameResponse Implements PlaylistService.ServiceSoap.updateClientName
            Return MyBase.Channel.updateClientName(request)
        End Function
        
        Public Function updateClientName(ByVal nickname As String, ByVal newClientNickName As String) As Boolean
            Dim inValue As PlaylistService.updateClientNameRequest = New PlaylistService.updateClientNameRequest()
            inValue.Body = New PlaylistService.updateClientNameRequestBody()
            inValue.Body.nickname = nickname
            inValue.Body.newClientNickName = newClientNickName
            Dim retVal As PlaylistService.updateClientNameResponse = CType(Me,PlaylistService.ServiceSoap).updateClientName(inValue)
            Return retVal.Body.updateClientNameResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PlaylistService_ServiceSoap_updatePlaylistName(ByVal request As PlaylistService.updatePlaylistNameRequest) As PlaylistService.updatePlaylistNameResponse Implements PlaylistService.ServiceSoap.updatePlaylistName
            Return MyBase.Channel.updatePlaylistName(request)
        End Function
        
        Public Function updatePlaylistName(ByVal nickname As String, ByVal playname As String, ByVal newPlayname As String) As Boolean
            Dim inValue As PlaylistService.updatePlaylistNameRequest = New PlaylistService.updatePlaylistNameRequest()
            inValue.Body = New PlaylistService.updatePlaylistNameRequestBody()
            inValue.Body.nickname = nickname
            inValue.Body.playname = playname
            inValue.Body.newPlayname = newPlayname
            Dim retVal As PlaylistService.updatePlaylistNameResponse = CType(Me,PlaylistService.ServiceSoap).updatePlaylistName(inValue)
            Return retVal.Body.updatePlaylistNameResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PlaylistService_ServiceSoap_getTrackInfo(ByVal request As PlaylistService.getTrackInfoRequest) As PlaylistService.getTrackInfoResponse Implements PlaylistService.ServiceSoap.getTrackInfo
            Return MyBase.Channel.getTrackInfo(request)
        End Function
        
        Public Function getTrackInfo(ByVal playname As String, ByVal trackID As String) As String
            Dim inValue As PlaylistService.getTrackInfoRequest = New PlaylistService.getTrackInfoRequest()
            inValue.Body = New PlaylistService.getTrackInfoRequestBody()
            inValue.Body.playname = playname
            inValue.Body.trackID = trackID
            Dim retVal As PlaylistService.getTrackInfoResponse = CType(Me,PlaylistService.ServiceSoap).getTrackInfo(inValue)
            Return retVal.Body.getTrackInfoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PlaylistService_ServiceSoap_updateTrack(ByVal request As PlaylistService.updateTrackRequest) As PlaylistService.updateTrackResponse Implements PlaylistService.ServiceSoap.updateTrack
            Return MyBase.Channel.updateTrack(request)
        End Function
        
        Public Function updateTrack(ByVal playname As String, ByVal trackID As String, ByVal title As String, ByVal location As String, ByVal duration As String) As Boolean
            Dim inValue As PlaylistService.updateTrackRequest = New PlaylistService.updateTrackRequest()
            inValue.Body = New PlaylistService.updateTrackRequestBody()
            inValue.Body.playname = playname
            inValue.Body.trackID = trackID
            inValue.Body.title = title
            inValue.Body.location = location
            inValue.Body.duration = duration
            Dim retVal As PlaylistService.updateTrackResponse = CType(Me,PlaylistService.ServiceSoap).updateTrack(inValue)
            Return retVal.Body.updateTrackResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PlaylistService_ServiceSoap_removeTrack(ByVal request As PlaylistService.removeTrackRequest) As PlaylistService.removeTrackResponse Implements PlaylistService.ServiceSoap.removeTrack
            Return MyBase.Channel.removeTrack(request)
        End Function
        
        Public Function removeTrack(ByVal playname As String, ByVal trackID As String) As Boolean
            Dim inValue As PlaylistService.removeTrackRequest = New PlaylistService.removeTrackRequest()
            inValue.Body = New PlaylistService.removeTrackRequestBody()
            inValue.Body.playname = playname
            inValue.Body.trackID = trackID
            Dim retVal As PlaylistService.removeTrackResponse = CType(Me,PlaylistService.ServiceSoap).removeTrack(inValue)
            Return retVal.Body.removeTrackResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PlaylistService_ServiceSoap_removePlaylist(ByVal request As PlaylistService.removePlaylistRequest) As PlaylistService.removePlaylistResponse Implements PlaylistService.ServiceSoap.removePlaylist
            Return MyBase.Channel.removePlaylist(request)
        End Function
        
        Public Function removePlaylist(ByVal playname As String) As Boolean
            Dim inValue As PlaylistService.removePlaylistRequest = New PlaylistService.removePlaylistRequest()
            inValue.Body = New PlaylistService.removePlaylistRequestBody()
            inValue.Body.playname = playname
            Dim retVal As PlaylistService.removePlaylistResponse = CType(Me,PlaylistService.ServiceSoap).removePlaylist(inValue)
            Return retVal.Body.removePlaylistResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PlaylistService_ServiceSoap_removeClient(ByVal request As PlaylistService.removeClientRequest) As PlaylistService.removeClientResponse Implements PlaylistService.ServiceSoap.removeClient
            Return MyBase.Channel.removeClient(request)
        End Function
        
        Public Function removeClient(ByVal nickname As String) As Boolean
            Dim inValue As PlaylistService.removeClientRequest = New PlaylistService.removeClientRequest()
            inValue.Body = New PlaylistService.removeClientRequestBody()
            inValue.Body.nickname = nickname
            Dim retVal As PlaylistService.removeClientResponse = CType(Me,PlaylistService.ServiceSoap).removeClient(inValue)
            Return retVal.Body.removeClientResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PlaylistService_ServiceSoap_voteOnPlaylist(ByVal request As PlaylistService.voteOnPlaylistRequest) As PlaylistService.voteOnPlaylistResponse Implements PlaylistService.ServiceSoap.voteOnPlaylist
            Return MyBase.Channel.voteOnPlaylist(request)
        End Function
        
        Public Function voteOnPlaylist(ByVal playname As String, ByVal score As Double) As Boolean
            Dim inValue As PlaylistService.voteOnPlaylistRequest = New PlaylistService.voteOnPlaylistRequest()
            inValue.Body = New PlaylistService.voteOnPlaylistRequestBody()
            inValue.Body.playname = playname
            inValue.Body.score = score
            Dim retVal As PlaylistService.voteOnPlaylistResponse = CType(Me,PlaylistService.ServiceSoap).voteOnPlaylist(inValue)
            Return retVal.Body.voteOnPlaylistResult
        End Function
    End Class
End Namespace
